### ISSUE TITLE
How do you send notifications to all users？

### ISSUE THREAD

**Issue by lou-lan** [sideshow/apns2#103]
Please ensure that you are using the latest version of the master branch before filing an issue.

Also make sure to include logs (if applicable) to help reproduce the issue by setting the `GODEBUG=http2debug=2` env var.

1. What version of Go are you using? `go version`
2. What OS and processor architecture are you using? `go env`
3. What did you do?
4. What did you expect to see?
Send notifications to all users.
5. What did you see instead?

**Comment by sideshow** [comment]
This library doest keep track of the list of devices/tokens as that is left for the developer to do.

Assuming your application already has a list of users and tokens, you would just iterate through the device tokens and send a notification to each device, similar to this:  

```go
for _, token := range tokens {
  notification := &apns2.Notification{
    DeviceToken: token,
    Topic: "my.topic",
    Payload: payload,
  }
  res, err := client.Push(notification) // send push
  ...
}
```
