### ISSUE TITLE
400 BadDeviceToken

### ISSUE THREAD

**Issue by zhejiananzhuren** [sideshow/apns2#105]
Hello,
          When I use example/basic/main.go,  I tried both release.p12 and debug.p12 file. 
release.p12 file got the "400 4878166F-52D8-92F3-171C-0B09A1320665 BadDeviceToken" . And debug.p12 file got the "Error:Post https://api.push.apple.com/3/device/f4418e50a544864f5d10d6e7254703255f357fd8d52f5c0a47301e00f7d8f09c: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
         Could you please help me with this problem.Thanks very much ,hoping for your response.

**Comment by liuweiming1997** [comment]
I have the same problem

**Comment by sideshow** [comment]
Thanks @TrayserCassa @liuweiming1997 This is a similar issue to https://github.com/sideshow/apns2/issues/109 so I'll add more docs

**Comment by sideshow** [comment]
Closing this off as @iranjith4 added some notes to the readme example
