### ISSUE TITLE
README file missing important information

### ISSUE THREAD

**Issue by stellmaurer** [sideshow/apns2#109]
Push notifications worked great in development mode, but once I published my application to the App Store, notifications stopped working. I ended up having to explicitly set the client environment like so:

`client := apns2.NewTokenClient(token)`
`client.Production()`

Please update the README file to say that you need to explicitly set the client to Production mode after you publish your app to the App Store.

**Comment by sideshow** [comment]
Closing this off as @iranjith4 added some notes to the readme example
