### ISSUE TITLE
iOS 12 Critical Alert Support

### ISSUE THREAD

**Issue by viparthasarathy** [sideshow/apns2#114]
`builder.go` currently expects `Sound` on the aps payload to be a string but iOS 12 supports passing in dictionaries for that field in order to send critical alerts.

See [this documentation](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification#2990112) for more information.

**Comment by sideshow** [comment]
Thanks for the PR @viparthasarathy - merged.
