### ISSUE TITLE
vendor/golang.org/x/net/http2/server.go:220: s.RegisterOnShutdown undefined (type *http.Server has no field or method RegisterOnShutdown)

### ISSUE THREAD

**Issue by newfotune** [sideshow/apns2#123]
1. What version of Go are you using? `go version`
go version go1.8.1 darwin/amd64

2. What OS and processor architecture are you using? `go env`
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/fortune/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/gf/f7r9_lpd03vbdy4577f5wxcc0000gq/T/go-build260535815=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

3. What did you do?
govendor fetch github.com/sideshow/apns2
Then try to run the JWT Token Example

4. What did you expect to see?
Push notification sent to my phone. I am able to do it via curl
5. What did you see instead?
vendor/golang.org/x/net/http2/server.go:220: s.RegisterOnShutdown undefined (type *http.Server has no field or method RegisterOnShutdown)

This looks like a version mismatch issue. Looks like the [RegisterOnShutdown](https://github.com/golang/go/issues/23132#issuecomment-351752122) function was added in go1.9. But according to the Readme of apns2, it should work on 1.6+

**Comment by KarlYan** [comment]
RegisterOnShutdown was added on go 1.9

**Comment by newfotune** [comment]
If you can't reproduce it, then i must have done something wrong. I upgraded to go 1.9 and it works.

**Comment by sideshow** [comment]
Thanks @newfotune I will close this issue
