### ISSUE TITLE
Fatal: Concurrent map read and write issue

### ISSUE THREAD

**Issue by sagarp-webonise** [sideshow/apns2#124]
I am using this package and concurrent go routines trying to Push() notification always results with fatal error of concurrent map read and write. Can you help me with sample example to avoid this fatal error?

**Comment by sideshow** [comment]
@sagarp-webonise Sure -- There are some examples in the `_example` folder of this repo. My guess is that you are doing something weird with the map when you are building the payload. 

I'm going to close this issue off, but feel free to re-open with more information about your environment and examples of your code if you think there is a bug. Thanks.
