### ISSUE TITLE
Invalid semver version tags makes the project unusable on modules

### ISSUE THREAD

**Issue by lopezator** [sideshow/apns2#126]
Semantic versioning approach (uses by go modules) propose using the following template to tag versions.

`v{major}.{minor}.{patch}`

Incorrect/incomplete tags (from a semantic versioning approach view) are not directly usable from go modules.

For example, latest version is tagged as `v0.15` (patch version missing), the valid semver tag would be `v0.15.0`.

Current `v0.15` tag would throw this error when doing a `go get` with `go modules` activated `GO111MODULE=on`:
```
go get github.com/sideshow/apns2@v0.15
go get github.com/sideshow/apns2@v0.15: no matching versions for query "v0.15"
```

** Solution: **

Tag the versions in github according to the semver specification:

https://semver.org/

**Comment by dvaldivia** [comment]
This would be super useful to be able to use this library with go modules that have been available since go 1.11 and 1.12 now going mainstream on Go 1.13

**Comment by Extrawurst** [comment]
This fork seems to be more maintained and supporting semVer: https://github.com/riftbit/apns2

**Comment by sideshow** [comment]
Thanks @lopezator and sorry this took so long to get to. New release here https://github.com/sideshow/apns2/releases/tag/v0.16.0
