### ISSUE TITLE
Development APNS endpoint is incorrect

### ISSUE THREAD

**Issue by tonyjhuang** [sideshow/apns2#135]
The new development endpoint is `api.sandbox.push.apple.com`

See https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns

The current endpoint is `https://api.development.push.apple.com`

https://github.com/sideshow/apns2/blob/c6554aff77e6e5580dec977c8c33cc238f329ab0/client.go#L22

This is manifesting itself in the form of `Client.Timeout` errors, see #24 

Looks like there's an open PR that addresses this: https://github.com/sideshow/apns2/pull/133

**Comment by leearmstrong** [comment]
This is in the docs now, is there a reason this has not been updated yet?

**Comment by sideshow** [comment]
@leearmstrong Yes the PR tests were failing. This has been fixed and merged now, thanks
