### ISSUE TITLE
url.Error "unexpected EOF"

### ISSUE THREAD

**Issue by dwieeb** [sideshow/apns2#14]
apns2 has been working great in production, for the most part. However, occasionally, I see inexplicable "unexpected EOF" errors. The error is a `&url.Error{Op:"Post", URL:"https://api.push.apple.com/3/device/<omitted>", Err:(*errors.errorString)(0xc82000a150)}`, where the `Err` property of the url error is "unexpected EOF". The error is not a [temporary](https://golang.org/pkg/net/url/#Error.Temporary) url.Error, so I assumed it may be an issue with my `apns2.Client`'s connection, which I am keeping open. So when I encounter the error, I remake the client (thus remaking the connection), but the error continues to happen (makes sense, it's a _permanent_ error). I'm just not sure what it could be, exactly. 

Any ideas for what this means or how I could debug? 

Using apns2 `a6f9928377a5bf0f0605e3410f2a13f286f7a5a9`.

**Comment by alissonsales** [comment]
From my experience this happens when you use an invalid certificate and the connection with APNs is not successful. I'd try to do the same request (same certificate) using something like curl/nghttp2 to confirm. I'm not sure how to detect this kind of error in advance with the current http client API.

**Comment by dwieeb** [comment]
Relevant: https://github.com/golang/go/issues/9424

As you mentioned there isn't a great way to detect such an error. It's bubbling up from deep within the bowels of Go's net package.

I'll do some research using other http2 tools to see what APNS is actually doing to the connection when this happens.
