### ISSUE TITLE
"apns-collapse-id" not replacing existing notification(s)

### ISSUE THREAD

**Issue by benguild** [sideshow/apns2#145]
This value is configured in the `Notification` struct, but it does not seem to have any effect. The notifications still show up individually, and must be cleared individually.

We were hoping to replace any previous one(s) and keep only the latest one, but it has no effect.

Is this normal? Or, is it broken?

**Comment by benguild** [comment]
Also, just to emphasize that it's not working, there's a Golang constant being set to it so there's no way the value can mutate. It's **always** the same for all pushes of that type, yet they stack up.

**Comment by sideshow** [comment]
We have use this in production and it works as expected. Also, I just double checked with the following code and it seems to be working correctly. Are you able to share your code/env details? Thanks

```
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"time"

	"github.com/sideshow/apns2"
	"github.com/sideshow/apns2/certificate"
	"github.com/sideshow/apns2/payload"
)

func main() {
	certPath := flag.String("cert", "", "Path to .p12 certificate file (Required)")
	token := flag.String("token", "", "Push token (Required)")
	topic := flag.String("topic", "", "Topic (Required)")
	flag.Parse()

	if *certPath == "" || *token == "" || *topic == "" {
		flag.PrintDefaults()
		os.Exit(1)
	}

	cert, err := certificate.FromP12File(*certPath, "")
	if err != nil {
		log.Fatal("Cert Error:", err)
	}

	t := time.Now()
	alert := fmt.Sprintf("Hello %s", t.Format(time.RFC1123))

	notification := &apns2.Notification{}
	notification.DeviceToken = *token
	notification.Topic = *topic
	notification.CollapseID = "test_collapse_id"
	notification.Payload = payload.NewPayload().Alert(alert)

	client := apns2.NewClient(cert) // .Production()
	res, err := client.Push(notification)

	if err != nil {
		log.Fatal("Error:", err)
	}

	fmt.Printf("%v %v %v\n", res.StatusCode, res.ApnsID, res.Reason)
}```

`go run main.go -cert ~/Certificates.p12 -token "5dc35xxx" -topic com.sideshow.apns2`

**Comment by benguild** [comment]
Weird. It's Go v1.11 and running on Google App Engine. — My guess would be that App Engine's URL client may potentially be to blame, given that this goes out as a header.
- https://cloud.google.com/appengine/docs/standard/go/issue-requests
- https://cloud.google.com/appengine/docs/standard/go/outbound-requests

I don't see any relevant restrictions on headers, but is there anything I can test to help narrow this down?

**Comment by sideshow** [comment]
Thats weird. Are you able to reproduce locally at all?. Its been a while since I tried to run this code with app engine but seem to recall you can run locally.

Also are you doing anything to hijack the notification on the iOS side that could be affecting the way it's collapsing? 

Also, something to note with iOS is that it will only collapse an untapped notification. ie, If you tap the notification and it gets removed from the notification centre, and then send a push with the same collapse ID it will show again.

**Comment by benguild** [comment]
I'm seeing the collapse ID populated in `notification.request.identifier` but it's not combining the notifications, so this might be an issue elsewhere. Is anything else required in the sideshow configuration for this to work?

**Comment by sideshow** [comment]
@benguild Nothing else is required. A Fresh app with the above code should work and correctly collapse notifications in the notification center. So to check I would try the go code above to push to you app. If you are still getting duplicates then it could be something you have done in the app

**Comment by sideshow** [comment]
@benguild Did you manage to get this working, or alternatively have you got any example code to reproduce the error? Thanks

**Comment by benguild** [comment]
I guess let's close, as I'm currently unable to work on this. I'll respond back if I have any new discovery.
