### ISSUE TITLE
400 InvalidPushType

### ISSUE THREAD

**Issue by bmueller** [sideshow/apns2#148]
I keep getting error 400 "InvalidPushType" from Apple's push notification service when trying to send a push with the new apns-push-type value set. 

This is how I'm setting up the notification:

		n := &apns2.Notification {
			DeviceToken: p.DeviceToken,
			Topic:       topic,
			CollapseID:	 p.CollapseID,
			Payload:     []byte(p.Payload),
			PushType: 	apns2.PushTypeBackground
		}

Am I doing something wrong with how I set the PushType property? Everything else is getting set correctly and pushes without this property set are getting sent just fine.

**Comment by sideshow** [comment]
Are you sending something that interacts with the user? ie, an alert badge or sound? 

From the apple docs: 

> Specify alert when the delivery of your notification displays an alert, plays a sound, or badges your app's icon. Specify background for silent notifications that do not interact with the user.

**Comment by bmueller** [comment]
No, I'm trying to use the background push type. (I also tried it with alert, and got the same error.) The weird thing is that this was working fine since I implemented it a week ago until mid-day today, when I started getting this error. Perhaps Apple flipped a switch to get things ready for iOS 13's rollout?

**Comment by sideshow** [comment]
Yeah seems weird. They could of changed something. What version of iOS are you trying to push to, and can you include a copy of your payload here. Thanks

**Comment by Extrawurst** [comment]
I think they started limiting the amount of background pushes u can sent to a device, maybe that's the problem

**Comment by treyrich** [comment]
@bmueller were you trying to send to a VOIP device token? I just discovered that apparently when trying to push to a voip device token you must include a different value for this header than documented. I've opened an issue here: #149

**Comment by iatsiuk** [comment]
in our case this error only occurs for VOIP push messages. For now we’ve made the following change at "sideshow/apns2" module:

<img width="699" alt="Screenshot 2019-09-21 at 14 28 31" src="https://user-images.githubusercontent.com/24681814/65372735-747e4b00-dc7c-11e9-9583-7c04a80d49bd.png">

**Comment by bmueller** [comment]
@treyrich this is for complication PushKit pushes, actually. Most of them appear to be going through (I'm sending 15k+ per hour), but a handful come back with an InvalidPushType error. And my own test device is *always* coming back with that error for some reason.

And @sideshow this is for an iOS 13 device.

**Comment by treyrich** [comment]
Interesting...yeah, I ran into this on my own testing device for voip pushes. Have you tried an alternative value for the header for complications? It’s fairly frustrating that Apple hasn’t documented this.

**Comment by bmueller** [comment]
@treyrich I just tried using "complication" for the alert type and I didn't get an InvalidPushType error. But I'm not actually receiving the push on my device, either.

**Comment by bmueller** [comment]
@treyrich woohoo, it's working now! I forgot that you have to have the Apple Watch app installed with the complication on your current watch face - I had deleted the app thinking maybe that would reset things, so that's why the push wasn't working before even though I was getting a 200 code from the push server.

So yes, the repo needs to be updated to accept a string for the push type, as it looks like "voip" and "complication" are now required for PushKit pushes instead of "background".

**Comment by sideshow** [comment]
This has been fixed now via #151 and the 6 possible values for apns-push-type have been added via #153
