### ISSUE TITLE
apns-push-type incorrect for voip pushes

### ISSUE THREAD

**Issue by treyrich** [sideshow/apns2#149]
I am attempting to switch to this library from a previous library. After a day of frustration on why I was constantly getting a InvalidPushType I started experimenting with curl and discovered the issue.

It appears that neither `background` nor `alert` are valid values when using PushKit for voip. My experiments were successful when I included `voip` for the header `apns-push-type` or excluded the the `apns-push-type` header altogether.

I have not yet been able to find documentation of this being expected behavior, but what I do know is that this is not working as the library is currently configured.

My suggestion would be to allow arbitrary values in the `apns-push-type` header until such time as someone can discover documentation for how to handle voip properly, that way users that need it can use the temporary (working) solution of setting the header to `voip` for the time being.

**Comment by treyrich** [comment]
Upon further investigation it appears that arbitrary values are allowed here, so I suppose that this issue can be closed? But I'll leave it open until we confirm whether or not it's worth adding new constant values for VOIP as it seems Apple wants a different value here.

**Comment by lz1irq** [comment]
If it is a valid push type, I think there should be a constant for it in the library. I've opened pull request #150 to add it.

**Comment by sideshow** [comment]
This is now fixed with https://github.com/sideshow/apns2/pull/151

Looks like Apple has added the more info to the allowed apns-push-type docs here https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns
