### ISSUE TITLE
Is there provide callback service?

### ISSUE THREAD

**Issue by zhaodragon99** [sideshow/apns2#159]
Forgive my pool english.
Now i have a question that response 200, means apns server return me success, not the meaning device received message.
1.Sent message to device response 200, and device received message successful.
2.Uninstall the application.
3.Then send message , why also response 200 too. 
![image](https://user-images.githubusercontent.com/8000755/70199482-c5b2bc80-174c-11ea-87e5-cc60745040d6.png)
So is there provide callback service, which callback when device receive message.
Waiting for your response,Thanks~

**Comment by alissonsales** [comment]
APNs does not state how long they take to invalidate tokens of devices that uninstalled the app. In my experience it can take several hours. To make the matter even worse, it will keep old tokens valid (for and undocumented time) if you uninstall and install the same app again.

To properly verify how long APNs is taking to invalidate a token you need to install an app, retrieve a token X, uninstall the app (don't install again) and periodically send pushes to token X. At some stage you'll receive an http 410 from APNs for that token.

Unfortunately there's endpoint/method on the HTTP/2 API to ask if a token is valid.

**Comment by zhaodragon99** [comment]
> APNs does not state how long they take to invalidate tokens of devices that uninstalled the app. In my experience it can take several hours. To make the matter even worse, it will keep old tokens valid (for and undocumented time) if you uninstall and install the same app again.
> 
> To properly verify how long APNs is taking to invalidate a token you need to install an app, retrieve a token X, uninstall the app (don't install again) and periodically send pushes to token X. At some stage you'll receive an http 410 from APNs for that token.
> 
> Unfortunately there's endpoint/method on the HTTP/2 API to ask if a token is active or not.

**Comment by zhaodragon99** [comment]
> APNs does not state how long they take to invalidate tokens of devices that uninstalled the app. In my experience it can take several hours. To make the matter even worse, it will keep old tokens valid (for and undocumented time) if you uninstall and install the same app again.
> 
> To properly verify how long APNs is taking to invalidate a token you need to install an app, retrieve a token X, uninstall the app (don't install again) and periodically send pushes to token X. At some stage you'll receive an http 410 from APNs for that token.
> 
> Unfortunately there's endpoint/method on the HTTP/2 API to ask if a token is active or not.

Thank you~

**Comment by sideshow** [comment]
Closing this as per @alissonsales comments, thanks!
