### ISSUE TITLE
Calling from PHP?

### ISSUE THREAD

**Issue by internalG** [sideshow/apns2#167]
I have a PHP project that needs to be upgraded to APNS HTTP/2. What's the best practice to use this GO project? If it has to be the command line, is the persist connection still available? Thanks.

**Comment by andreyvit** [comment]
@internalG You can write a Golang wrapper server, compile it, run it as a daemon on your server, and communicate with it via HTTP (or any other protocol of your choice). There's nothing you can use out of the box, though.

**Comment by internalG** [comment]
@andreyvit Thanks. That's the answer.
