### ISSUE TITLE
does support field, aps:imageAbsoluteString?。 this is a common situation to push image to app!

### ISSUE THREAD

**Issue by YK-peng** [sideshow/apns2#170]
Please ensure that you are using the latest version of the master branch before filing an issue.

Also make sure to include logs (if applicable) to help reproduce the issue by setting the `GODEBUG=http2debug=2` env var.

1. What version of Go are you using? `go version`
2. What OS and processor architecture are you using? `go env`
3. What did you do?
4. What did you expect to see?
5. What did you see instead?

**Comment by YK-peng** [comment]
{
    "aps": {
        "alert": "This is some fancy message.",
        "badge": 1,
        "sound": "default",
        "mutable-content": "1",
        "imageAbsoluteString": "http://upload.univs.cn/2012/0104/1325645511371.jpg"
        
    }
}


![](http://static.zybuluo.com/coderXu/14wg6zmz6ta1uanpmbgwayn8/QQ20160927-9.png)

**Comment by sideshow** [comment]
@YK-peng Please add a link to the apple push docs where i can see this string. Also pull requests are accepted if you would like to modify (as long as its a standard payload). Thanks

**Comment by sideshow** [comment]
Closing this off as after further investigation it looks like imageAbsoluteString is not referenced in the apple docs. Feel free to re-open and link to the docs if im wrong. Thanks
