### ISSUE TITLE
ask a question for usage

### ISSUE THREAD

**Issue by lshaocheng** [sideshow/apns2#174]
If I have multiple messages, can I push them all at once?

**Comment by sideshow** [comment]
Yes, you can push multiple messages by calling `client.Push(notification)` many times with a seperate notification intended for each device. Underneath its using a the same persistent HTTP/2 connection so this will be very fast. There is an example of sending multiple messages with a channel here https://github.com/sideshow/apns2/blob/master/_example/channel/main.go
