### ISSUE TITLE
Support for apns-push-type in header

### ISSUE THREAD

**Issue by satheesh-moorthy** [sideshow/apns2#175]
Hi,

Is there any plan to add support for  apns-push-type. 

iOS 13 introduced a new and required header called apns-push-type. The value of this header informs APNs of the contents of your notification’s payload so that APNs can respond to the message appropriately. The possible values for this header are:

alert
background
voip
complication
fileprovider
mdm

https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns

**Comment by sideshow** [comment]
@satheesh-moorthy This is already supported.
Example would be as follows:  

```go
notification := &apns2.Notification{
    PushType: apns2.PushTypeBackground
    ...
}
```

You can see more examples via tests here https://github.com/sideshow/apns2/blob/991ef5658ed1d8f5003f9b4b7e0a40c0cd0121bd/client_test.go#L230

Thanks

**Comment by satheesh-moorthy** [comment]
Hi @sideshow  , Thanks a lot for the information
