### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by linkthrow** [sideshow/apns2#179]
I'm running this package to send prod(testflight) push notifications, I am using the p8 key to authenticate the server, but getting the following error:

`
Post "https://api.push.apple.com/3/device/xxx": x509: certificate signed by unknown authority
`

anyone have any idea what is causing this?

**Comment by linkthrow** [comment]
For anyone else who encounters this, its because the Docker image I had didn't have the `ca-certificates` package installed

**Comment by sorliem** [comment]
I am encountering this issue as well @linkthrow I'll try making sure they are installed

**Comment by sorliem** [comment]
ah worked for me. 
```
apk add ca-certificates
```
Thanks!
