### ISSUE TITLE
Please drop Hyper and consider using http

### ISSUE THREAD

**Issue by thierryba** [sideshow/apns2#184]
Not an issue per se and I don't even know if it is feasible but hyper has received 0 updates in years.

**Comment by extrawurst** [comment]
Last hyper **release** was 20 days ago: https://github.com/hyperium/hyper/releases/tag/v0.14.5
I don’t see the Problem?

**Comment by thierryba** [comment]
oh wow, I was alway looking at pipit and that page was not up-to-date...
