### ISSUE TITLE
remote error: error decrypting message

### ISSUE THREAD

**Issue by samblabla** [sideshow/apns2#26]
Use '_example / main.go', run returns an error
`2016/05/31 15:39:42 Error: Post https://api.development.push.apple.com/3/device/269ccfa053618d819aa4e7150455e04163bf6b0f9d598affc9a596b7d215222f: remote error: error decrypting message`

Version go1.6.2

**Comment by sideshow** [comment]
This looks like its may be a problem with your certificate. Are any of your working?
Try regenerating your push certificate.

**Comment by sideshow** [comment]
@samblabla This looks like its coming from the tls package, which leads me to believe it is definitely a tls issue. Is this still happening? Have you tried re-generating your APNs certificate, and do you have any more information around your environment and the way you are using APNS2?

**Comment by samblabla** [comment]
How to generate the correct push certificate?

**Comment by samblabla** [comment]
Solve the problem, issue the certificate

**Comment by tinamina12** [comment]
I am also facing this issue, please let me know how to resolve this error.
