### ISSUE TITLE
Can I send multi-request on one apns client without any lock？

### ISSUE THREAD

**Issue by NetWilliam** [sideshow/apns2#32]
I was argueing with my colleague wheather I can write code like that

client = apns.NewClient(...)
for i := array {
go sendpush(client)
}

Can I send push req without lock?
where is the mechanism that make sure the validation of http2 frame on that tcp connection? i am looking for details but haven't got yet

**Comment by nathany** [comment]
HTTP/2 supports multiple streams and Go's http2 library will use an existing connection if one is open, so yes you can send multiple pushes as you describe.

However, if the array you are looping over contains a large or unknown number of notifications, you will probably want a worker pool. That way you can limit it to send, say, 50 pushes at a time at most.

**Comment by NetWilliam** [comment]
https://golang.org/src/net/http/transport.go?s=9639:9701#L1000
it should be at here, there is a channel work, all round-trip must write to this channel to get request send by http long connection 
thank you :-)
