### ISSUE TITLE
Apns2 error: dial udp 114.114.114.114:53: i/o timeout

### ISSUE THREAD

**Issue by jiangyilong** [sideshow/apns2#39]
Hi:
   when I  push apns notice, it return  dial udp 114.114.114.114:53: i/o timeout. I think the APNS2 can't connect the Apple's server. How can I fix it?
Below is the error:  
[16:45:44 CST 2016/09/06] [EROR] (main.pushApnsAndSaveException:125) Error:%!(EXTRA *url.Error=Post https://api.development.push.apple.com/3/device/3f8b4ecbae42914c2aa84300d300f8d2f55f5c7f96ea3770846f0c011c
07a8a5: dial tcp: lookup api.development.push.apple.com on 114.114.114.114:53: dial udp 114.114.114.114:53: i/o timeout)
[16:45:44 CST 2016/09/06] [INFO] (main.pushApnsAndSaveException:128) client res: %!(EXTRA *apns2.Response=<nil>)
[16:45:46 CST 2016/09/06] [EROR] (main.pushApnsAndSaveException:143) push again Error: %!(EXTRA *url.Error=Post https://api.development.push.apple.com/3/device/3f8b4ecbae42914c2aa84300d300f8d2f55f5c7f96ea3770846f0c011c
07a8a5: dial tcp: lookup api.development.push.apple.com on 114.114.114.114:53: dial udp 114.114.114.114:53: i/o timeout)
[16:45:46 CST 2016/09/06] [EROR] (main.pushApnsAndSaveException:146) push again fail

Only the first build the push connection has this error.

here is mine code:
func pushApnsAndSaveException(message []byte, client *apns.Client) {
	pMsg := pMessage.PushMessage{}
	json.Unmarshal(message, &pMsg)

	payload := NewPayload()
	payload.Alert(pMsg.Content)
	payload.Badge(pMsg.Count)
	payload.Custom("id", pMsg.Id)
	payload.Custom("type", pMsg.Type)
	payload.Custom("contentType", pMsg.ContentType)
	payload.Sound("sms-received1.caf")

	payloadByte, err := json.Marshal(payload)
	if err != nil {
		log.Println("json marshal error:", err)
	}

	log.Println("payload json: ", string(payloadByte))
	notification := &apns.Notification{}
	notification.DeviceToken = pMsg.Token

	notification.Topic = apnsConst.ApnsTopic
	notification.Priority = 10
	notification.Payload = payloadByte
	l4g.Info("payload btye: ", string(payloadByte), ",payload: ", notification.Payload)
	res, err := client.Push(notification)
        .........
}

the variable client *apns.Client is global.

**Comment by betrok** [comment]
It isn't even APNs IP. I guess you have troubles with DNS/firewall/proxy.

**Comment by sideshow** [comment]
@betrok you bet me to it. @jiangyilong The IP in your stacktrace `114.114.114.114` is not an Apple address, which means you are most likely behind some sort of proxy which is hijacking the request.
This could be the cause of you notifications not getting through in #38 too.

**Comment by sideshow** [comment]
@jiangyilong Did you manage to get your issue solved and get past your proxy?

**Comment by jiangyilong** [comment]
ok. i close it. maybe environment problem.
