### ISSUE TITLE
iOS 10 features not supported - e.g. thread-id on aps dictionary.

### ISSUE THREAD

**Issue by nordicio** [sideshow/apns2#40]
In payload/builder.go:

```
type aps struct {
        ...
	ThreadID   string         `json:"thread-id,omitempty"`
}
```

```
func (p *Payload) ThreadID(id threadID) *Payload {
	p.aps().ThreadID = threadID
	return p
}
```

**Comment by nathany** [comment]
Hi Andreas,

Apple hasn't yet updated the [The Remote Notification Payload](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/TheNotificationPayload.html#//apple_ref/doc/uid/TP40008194-CH107-SW1) documentation for iOS 10, but I'm told that it's coming soon. Do you have any publicly available reference to `thread-id` and what it does? I don't see any reference in the slides from WWDC 2016.

Until this is supported, you can serialize whatever JSON you like to send to `service.Push`.

Nathan.

**Comment by nordicio** [comment]
Hi Nathan,

oh! That's true. My bad.
Better wait for the official documentation.

Thanks,
Andreas

**Comment by sideshow** [comment]
Looks like this has been added to the apple docs now, so i'll go ahead and add it https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/APNsProviderAPI.html#//apple_ref/doc/uid/TP40008194-CH101-SW6
