### ISSUE TITLE
Document ClientManager and concurrent access safety

### ISSUE THREAD

**Issue by oliverjanik** [sideshow/apns2#44]
Can clients be used from multiple goroutines?

Is it recommended to keep an instance of client laying around or just create a new one per batch?

**Comment by sideshow** [comment]
Thanks for logging this issue. 

I will keep this issue open until more docs have been added, but to answer your question in the meantime;

It is safe to use client from multiple go routines. You should keep a client lying round and use the same client.

There is a comment on the method https://github.com/sideshow/apns2/blob/feature-auth-token/client.go#L51, but agree this needs clarifying in the docs.

The connection manager has been added in the last few days. It is designed to be used when you have multiple connections with different certs (ie, you are sending to multiple apps)

I will add some more docs in the coming days to better explain.

**Comment by sideshow** [comment]
Closing this as more docs will be added as part of https://github.com/sideshow/apns2/issues/54
