### ISSUE TITLE
Loading .p12 certificate: ans1: indefinite length found (not DER)

### ISSUE THREAD

**Issue by gngeorgiev** [sideshow/apns2#46]
Hello,

I am trying to use the apns2 module but when I try to load the p12 file I get the following error

```
ans1: indefinite length found (not DER)
```

I was able to convert the file to `.pem` using the command line openssl, and it worked but this is not an ideal solution, I need to be able to use the p12 file directly or convert it to pem at runtime. Sadly the openssl bindings do not offer this functionality as of now. Any suggestions?

**Comment by sideshow** [comment]
@gngeorgiev thanks for logging. 
I haven't seen this before, so are you able to share more info about your environment and your cert. 

- Did you export the .p12 yourself and if so was it from keychain using a similar process to this (https://software.intel.com/en-us/xdk/articles/walkthrough-export-p12-file)
- Have you tried re-generating the `.p12` ?
- Have you tried other `.p12` certificates.
- What version of openssl are you running?

**Comment by sideshow** [comment]
@gngeorgiev did you manage to get any further on this?

**Comment by gngeorgiev** [comment]
@sideshow Yeah, I did.

Turns out my certificates were indeed a bit weird, since regenerating them fixed the problems. However, I needed the old ones to work, since I need to be able to handle arbitrary use cases. In the end I ended up using the `openssl` command line tool, passing certificates in stdin and getting the decoded certificate and private key from stdout. I don't think there is anything you can do except document this case.

**Comment by sideshow** [comment]
Thanks @gngeorgiev I have added a separate issue to add more docs around this. https://github.com/sideshow/apns2/issues/54
