### ISSUE TITLE
Status 403 : MissingProviderToken

### ISSUE THREAD

**Issue by Fantasim** [sideshow/apns2#47]
Hi,

I'm trying apns2 to manage push notification on my iOS app, but i get this response : 

Reason:  MissingProviderToken
Status:  403

what did I forget?

```
var (
    Certificate tls.Certificate
)

func InitClient(){
    Certificate, _ = certificate.FromPemFile("./cert.pem", "")
}

func SendNotificationIOS(alert string, deviceToken string) bool {

    notification := &apns.Notification{}
    notification.DeviceToken = deviceToken
    notification.Topic = "BUNDLE_IDENTIFIER"
    notification.Payload = []byte(`{"aps":{"alert":"Hello!"}}`)
    client := apns.NewClient(Certificate).
    res, err := client.Push(notification)

    fmt.Println("APNs ID: ", res.ApnsID)
    fmt.Println("Reason: ", res.Reason)
    fmt.Println("Status: ", res.StatusCode)
    if err != nil {
        return false
    }
    return true
}
```

**Comment by sideshow** [comment]
You're getting a 403 because theres something wrong with your cert and you're not catching the err and using `_` instead.

**Comment by Fantasim** [comment]
Thanks, error actually came from there.

Actually, i've a status 200, but my device doesn't receive notification. I know it's not about package and i'm sorry to ask it here but it's first time i'm use push notification and I have already asked for help on stackoverflow but nobody could help me.

So everything seems to work but my iphone doesn't receive notification sent, do you know why or where the problem might be?

**Comment by sideshow** [comment]
No probs. If you're getting a 200 then it means it was successfully sent and accepted by APNS, so i would look to the device code and maybe check the following;

1. You don't have the app open when testing - Unless you've written extra code to show a notification when the app is open it wont show when the app is open.
2. You haven't requested the correct permissions from the user - On the latest version of iOS all devices will receive push tokens, and you can push to all devices by default, but alerts badges and sounds wont display unless you have requested the correct permissions.

**Comment by Fantasim** [comment]
Oh my god!!!!! Thank you, I thought notification appeared even when the application was open! it works perfectly! thanks again ! :)

**Comment by sideshow** [comment]
Haha, no worries. Glad i could help!
