### ISSUE TITLE
Missing Reason consts

### ISSUE THREAD

**Issue by powerman** [sideshow/apns2#48]
Comparing to current https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW1 these are missing (probably only first is valid for this package):
```
BadCollapseId
ExpiredProviderToken
InvalidProviderToken
MissingProviderToken
TooManyProviderTokenUpdates
```

**Comment by sideshow** [comment]
Great catch, looks like Apple have updated the reason code table. 
Will add these before merging https://github.com/sideshow/apns2/pull/43
