### ISSUE TITLE
Why I don't get notification when apns2 sends notification successfuly.

### ISSUE THREAD

**Issue by TianDaGe** [sideshow/apns2#55]
hello, i am trying to get notification on my ios app,
apns2 is working fine like this. but my app is not getting notification. 

2016/11/27 13:00:12 APNs ID: BA5AED23-31F3-77A6-9E8E-C9C0274ACEE0

of course, I did all things correctly on app side.
I checked my app with other php sample. this is php sample(apns not apns2) url link.
https://www.raywenderlich.com/123862/push-notifications-tutorial

You use  
	HostDevelopment = "https://api.development.push.apple.com"
	HostProduction  = "https://api.push.apple.com"

But he uses (php sample)
        ssl://gateway.sandbox.push.apple.com:2195

How will I do?
My golang version is 1.7.3
cert.pem is Apple Developer IOS Push Services cert file. 
OS: windows 10

**Comment by TianDaGe** [comment]
![untitled](https://cloud.githubusercontent.com/assets/15997235/20647481/4b13746a-b4d0-11e6-94cf-155ebb902eb0.png)

**Comment by TianDaGe** [comment]
What am I wrong?

**Comment by sideshow** [comment]
@TianDaGe I suspect its because you are logging the id but not checking the status. 
The Response struct contains more info about wether of not it was sent (https://github.com/sideshow/apns2#response-error-handling)

try logging out the status code and reason (not just the id);

```go
	if err != nil {
		log.Fatal("Error: ", err)
	} else {
		fmt.Printf("%v %v %v\n", res.StatusCode, res.ApnsID, res.Reason)
	}
```

**Comment by TianDaGe** [comment]
oh this is bad token
400 7775245D-965C-8EE1-FE9C-7D7574DAE5EB BadDeviceToken

**Comment by sideshow** [comment]
This is probably because you are trying to send a push to a development device using the production gateway or a production device with the development gateway.

If this is a development device you must send to the development gateway;

So instead of this;

```go
client := apns.NewClient(cert).Production()
```

Do this;

```go
client := apns.NewClient(cert).Development()
```

**Comment by TianDaGe** [comment]
wow~perfect!!! very thanks a lot. Hahahaha

**Comment by TianDaGe** [comment]
sir, I will ask one more.
Generally, almost phones are getting notification.
But iPhone7 is not getting notification. They are using same app and getting device token by same method.

400 D9B05574-6377-0983-3D13-92FC26A34EF7 BadDeviceToken
Error is BadDeviceToken.
What am I wrong? or what does iPhone7 have issue on device token side?

**Comment by TianDaGe** [comment]
I got error reason. one is created development mode, and one is created production mode.
These are using same app that is published on the TestFlight.
Is this issue possible? anyway it is my mistake. thanks again.

**Comment by michaeltansytp** [comment]
@TianDaGe hi, so have you solved the testflight issue? Currently for testflight version I use host production and able to receive the push notification. However sometimes the testflight version doesn't receive the push notification. I checked from server log that the notification was sent with status 200 and no error reason

**Comment by TianDaGe** [comment]
Yes, I did. In the past, I used notification server separately for Development and Production cases.
