### ISSUE TITLE
Safe for use from concurrent goroutines?

### ISSUE THREAD

**Issue by carbocation** [sideshow/apns2#6]
Is the client safe for use from concurrent goroutines?

**Comment by sideshow** [comment]
Yes it it - It uses the underlying `Transport` which is safe for concurrent use by multiple goroutines. We are using it in production in this manner.

**Comment by carbocation** [comment]
I think it's worth mentioning this in the comments (for example, [database/sql](https://golang.org/pkg/database/sql/#DB) does so). I can create a pull request if that would be worthwhile.

**Comment by sideshow** [comment]
Great idea, yes please!

**Comment by sagarp-webonise** [comment]
To avoid fatal error of concurrent map read and write, are you using Push or PushWithContext? I am using this package and concurrent go routines trying to Push() notification always results with fatal error. Can you help me with sample example to avoid this fatal error?
