### ISSUE TITLE
http2 transport errors

### ISSUE THREAD

**Issue by udf2457** [sideshow/apns2#60]
Hi,

Setup as per your readme, substituting notification.DeviceToken and notification.Topic for my own.

I'm getting the following error:

`2016/12/11 10:28:39 Error:Post https://api.push.apple.com/3/device/<my_hex_id_goes_here> : http2: Transport: peer server initiated graceful shutdown after some of Request.Body was written; define Request.GetBody to avoid this error`

If it makes any difference, this is with go version go1.7.4 linux/amd64

**Comment by sideshow** [comment]
@udf2457 Can you give more information;

How often are you getting this error?
How many push notifications are you sending?
Are you holding on to the apns2 `Client` and not creating a new one each time>
Can you share your full http2 debug log?

**Comment by udf2457** [comment]
Hi Adam,

Sorry my bad.  I meant to come back here to update.

The answer was simple (although I guess it would have been nice for your code to handle the error differently) .... the answer is that your code defaults to the Production APNS service and I was testing on Dev. APNS.

**Comment by sideshow** [comment]
Thanks @udf2457. It should return `BadDeviceToken` in this case so i am unsure what actually happened. I will go ahead and close this off for now.

**Comment by kuchlous** [comment]
I was also getting the same error when I used production apns server instead of dev by mistake.

**Comment by sideshow** [comment]
@kuchlous Thats interesting, I haven't seen this before but good to know
