### ISSUE TITLE
Apple voip push support?

### ISSUE THREAD

**Issue by zeljko-bulatovic** [sideshow/apns2#71]
Hi,

Is this library support apple voip push? If yes, can you provide us example how to send this kind of notification?

Thanks !

**Comment by sideshow** [comment]
@zeljko-bulatovic my understanding from reading the docs is that it *should* support VOIP, without modification. It looks like you have to create a seperate certificate with the correct provisioning credentials, change the code on the iOS side and use a different topic to push to but everything else looks the same. I will keep this issue open until someone can confirm (hopefully you) by way of building an example app to test. Thanks

**Comment by zeljko-bulatovic** [comment]
Hi,

Yes you are correct! 

Separate certificate should be provided, with VOIP push support, and **very important is** not to provide topic for the notification on the server side, else you will receive error like "DeviceTokenNotForTopic"!

For iOS side, just follow any tutorial for voip push notifications, and everything should work correctly!

**Comment by sideshow** [comment]
That great, @zeljko-bulatovic
So were you able to get VOIP push going without modification to APNS2? If so I will go ahead and close this and add it to the readme.

**Comment by zeljko-bulatovic** [comment]
Yes, everything worked without any modifications to your library :)

**Comment by syauqisabili** [comment]
can you give me example for this?
