### ISSUE TITLE
When the TLS connection was builded?

### ISSUE THREAD

**Issue by xlionet** [sideshow/apns2#73]
I write my `push` operation according with the demo in ReadMe.md, but i am confused with the follwings:
```
client := apns2.NewClient(cert)
...
res, err := client.Push(notification)
```

so, when the connection was builded? when the DialTLS (client.HTTPClient.Transport.(*http2.Transport).DialTLS("tcp", "127.0.0:1", nil)) was called ?

**Comment by xlionet** [comment]
So, when the TLS initiation finised? According to the Apple`documents :

Provider      --------TLS initiation-------->    APNs
Provider    <-------------certificate--------   Provider

I am confused that I can not find relation code block  in your project.

Expect for ur reply, thx!

**Comment by nathany** [comment]
Hi Passi,
`NewClient` configures the HTTP/2 certificate and the Dialer: https://github.com/sideshow/apns2/blob/master/client.go#L56

But I'm not sure if it actually dials and does the TLS initiation at that point or later on. That is all handled internally by the [x/net/http2 package](https://godoc.org/golang.org/x/net/http2).

**Comment by xlionet** [comment]
Thank for your reply,  I found a annotation about this topic 
https://github.com/sideshow/apns2/blob/master/client.go#L46

Maybe it`s no need for me to figure out about the initiation of TLS in my project, I just confused and I will keep learn about it.
Thank u so much, have a good day~

**Comment by sideshow** [comment]
Hi @xlionet. Looks like you found what you were after -- I'm going to close this issue off, but will add a little more to expand on what @nathany said incase anyone else is curious.

`NewClient`sets up the TLS connection but does not dial it. 
The first dial is initiated when the first `Push` is called. The golang HTTP Client handles this TLS connection transparently and knows to connect or reconnect if there is no connection. 
If you don't call Push then the Client will not dial.
