### ISSUE TITLE
How to use proxy server for send apple push notification..

### ISSUE THREAD

**Issue by rakesh-eltropy** [sideshow/apns2#74]
We can send android push notification through proxy using following

```
transport := &http.Transport{Proxy: http.ProxyURL(proxyUrl)}
client := &http.Client{Transport: transport}
sender := &gcm.Sender{ApiKey: viper.GetString("pushNotification.gcmAPIKey"),Http:client}
```
but apns2 is using http2 and http2 transport doesn't have any way to set the proxyUrl.

Is it possible to send apple push notification through proxy server?

**Comment by nathany** [comment]
I'm not familiar with using proxies in Go, but it might be possible based on this article.
> "TLS connection has nothing to do with proxy, TLS is available as a addon to an already existing TCP connection." http://blog.abhijeetr.com/2016/02/golang-creating-https-connection-via.html

http2 starts as an http connection that is upgraded, much like TLS (https). You can do that in Go with `http2.ConfigureTransport`:

```go
config := &tls.Config{
    Certificates: []tls.Certificate{cert},
}
config.BuildNameToCertificate()

transport := &http.Transport{Proxy: http.ProxyURL(proxyUrl), TLSClientConfig: config}

if err := http2.ConfigureTransport(transport); err != nil {
	return nil, err
}
```
Derived from: https://github.com/RobotsAndPencils/buford/blob/master/push/service.go#L44

Please follow up with whether or not this works for you. Thanks.

**Comment by rakesh-eltropy** [comment]
Thanks a lot @nathany. It works for me.

**Comment by sideshow** [comment]
Thanks @nathany & @rakesh-eltropy 
I will close this issue since it worked

**Comment by riemers** [comment]
i actually need the same thing, using a proxy. Are there any options for getting it off the environment? With http you can do
```
Proxy: http.ProxyFromEnvironment
```
See similar example [here](https://github.com/jostyee/mattermost-push-proxy/blob/afc24b9e744f8657806dfdfb791e878e257dfa9b/server/push_notification.go#L33)

Is there a way similar for http2? That way it can just be added instead of having to do 'edits'
