### ISSUE TITLE
How can i push multiple notifications in one time?

### ISSUE THREAD

**Issue by xlionet** [sideshow/apns2#75]
The delay is too long for me while pushing notifications one by one, i am seeking for a way that could push a batch of notifications in a time, is there any suggestions for me?

**Comment by themartorana** [comment]
How many are you pushing? I send millions a day with no problem. I have a wrapper APNS manager for each certificate:

```
type apnsManager struct {
	Name   string
	Client *apns2.Client

	certFile string
}

type notificationQueue struct {
        notifications []apns2.Notification
        sync.Mutex
}
```

Then I enqueue notifications into a shared , while the manager just loops over notifications in a goroutine. That said, if you're seeing things move too slowly, you could have a number of Client instances pulling out of a queue as well.

Cheers,

Dave

**Comment by xlionet** [comment]
Thank u guys, it helps me a lot.  :-)

**Comment by nathany** [comment]
I took a slightly different approach from @themartorana in my push notification library, but either way, you can use goroutines to do multiple push notifications at once.

https://github.com/RobotsAndPencils/buford/blob/master/push/queue.go

**Comment by sideshow** [comment]
@xlionet also see the channel example in the _examples directory https://github.com/sideshow/apns2/blob/master/_example/channel/main.go

**Comment by sideshow** [comment]
Closing this off now as it looks to have worked for you.

**Comment by xlionet** [comment]
Yeah, thank ur guys
