### ISSUE TITLE
Pushkit support?

### ISSUE THREAD

**Issue by evnpr** [sideshow/apns2#96]
Hi, I saw in README that this library support Pushkit, but I cannot find the implementation as well as the base url of gateway.push.apple.com for Pushkit send notification. Is there any example or explanation regarding the pushkit implementation?

**Comment by sideshow** [comment]
Hi @evnpr 
I don't have a example for PushKit sorry, However there is nothing specific about PushKit on the APNs side other than using the correct certificate when pushing, therefore this should just work using the same approach as a standard notification. `gateway.push.apple.com` is the old gateway for the the TCP socket based protocol - Most of the examples on the net will reference this pre HTTP/2 gateway. The HTTP/2 equivalent is `api.push.apple.com` https://github.com/sideshow/apns2/blob/master/client.go#L23

There is a lack of examples out there for HTTP/2 and iOS 10+ however if you do get this working please update so we can add something to the docs.

**Comment by sideshow** [comment]
Closing this off for now but feel free to submit a PR if you would like to add more info to the docs. Thanks!
